from django.shortcuts import render
from .forms import DataForm
from .utils.summo_calculator import calculate
import pandas as pd
import numpy as np

def index(request):
    price = 0
    if request.method == 'POST':
        form = DataForm(request.POST)
        if form.is_valid():  # バリデーションを実行
            initial_data = form.cleaned_data  # 送信されたデータを初期値として使用
            form = DataForm(initial=initial_data)  # 初期値付きの新しいフォームを作成
            
            new_data = pd.DataFrame({
    '築年数': np.int16cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    '階': np.int32cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    '管理費': np.int32cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    '専有面積': np.float64cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    '賃貸アパート': np.bool_cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    '賃貸テラス・タウンハウス': np.bool_cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    '賃貸マンション': np.bool_cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    '賃貸一戸建て': np.bool_cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    '区': pd.Categoricalcleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    '最寄り駅': pd.Categoricalcleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    '歩分': np.int64cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    '地下階数': np.int64cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    '地上階数': np.int64cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    '居室': np.int64cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    'S': np.int64cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    'L': np.int64cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    'D': np.int64cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
    'K': np.int64cleaned_data['type']
cleaned_data['year']
cleaned_data['stairs']
cleaned_data['fee']
cleaned_data['area']
cleaned_data['ward']
cleaned_data['station']
cleaned_data['walk']
cleaned_data['fullbasement']
cleaned_data['fullstairs']
cleaned_data['rooms']
cleaned_data['sldk']),
})
            price = calculate(new_data)
        else:
            # フォームが無効な場合の処理 (エラーメッセージを表示するなど)
            pass
    else:
        form = DataForm()
        
    my_dict = {
        "forms":form,
        "price":price
    }
    
    return render(request,"index.html",my_dict)
