from django.shortcuts import render
from .forms import DataForm
from .utils.summo_calculator import calculate
import pandas as pd
import numpy as np

def index(request):
    price = 0
    if request.method == 'POST':
        form = DataForm(request.POST)
        if form.is_valid():  # バリデーションを実行
            initial_data = form.cleaned_data  # 送信されたデータを初期値として使用
            form = DataForm(initial=initial_data)  # 初期値付きの新しいフォームを作成
            
            new_data = pd.DataFrame({
    '築年数': np.int16(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    '階': np.int32(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']
    '管理費': np.int32(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    '専有面積': np.float64(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    '賃貸アパート': np.bool_(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    '賃貸テラス・タウンハウス': np.bool_(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    '賃貸マンション': np.bool_(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    '賃貸一戸建て': np.bool_(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    '区': pd.Categorical(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    '最寄り駅': pd.Categorical(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    '歩分': np.int64(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    '地下階数': np.int64(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    '地上階数': np.int64(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    '居室': np.int64(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    'S': np.int64(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    'L': np.int64(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    'D': np.int64(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
    'K': np.int64(initial_data['type']
            initial_data['year']
            initial_data['stairs']
            initial_data['fee']
            initial_data['area']
            initial_data['ward']
            initial_data['station']
            initial_data['walk']
            initial_data['fullbasement']
            initial_data['fullstairs']
            initial_data['rooms']
            initial_data['sldk']),
})
            price = calculate(new_data)
        else:
            # フォームが無効な場合の処理 (エラーメッセージを表示するなど)
            pass
    else:
        form = DataForm()
        
    my_dict = {
        "forms":form,
        "price":price
    }
    
    return render(request,"index.html",my_dict)
